org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Ditambahkan untuk mengatasi error "this and base files have different roots"
# saat build APK -- bug Kotlin incremental compiler kalau folder project dan
# Pub Cache ada di drive Windows yang beda (D: vs C:).
kotlin.incremental=false